# -*- coding: utf-8 -*-
"""drone (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12HqUHZiPhXb390Im1JyeYnLpmhJzciYx
"""

# Load the Drive helper and mount
from google.colab import drive
drive.mount('/content/drive')

cd /content/drive/MyDrive/yolov

pwd

# !git clone https://github.com/WongKinYiu/yolov7.git

cd yolov7

from google.colab import drive
drive.mount('/content/drive')

# pip install -r requirements.txt

# !python train.py --weights yolov7.pt --data "/content/drive/MyDrive/yolov/yolov7/data/custom.yaml" --workers  4 --batch-size 16 --img 600 600 --cfg cfg/training/yolov7.yaml --name yolov7 --hyp data/hyp.scratch.p5.yaml --epochs 80

!python detect.py --weights /content/drive/MyDrive/yolov/yolov7/best.pt --source "/content/image12.jpg"



"""# New section"""